#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE="dokku/$APP"; APP_PATH="$DOKKU_ROOT/$APP"

# Ensure the .dokku-git-rev file actually exists
[[ ! -f "$APP_PATH/.dokku-git-rev" ]] exit 0

# Grab the REV
GIT_REV=$(cat "$APP_PATH/.dokku-git-rev" | tail -1)

# Cleanup
rm "$APP_PATH/.dokku-git-rev"

# Push the GIT_REV to the docker image
id=$(echo "export GIT_REV=$GIT_REV" | docker run -i -a stdin $IMAGE /bin/bash -c "cat > /app/.profile.d/git_rev.sh")
test $(docker wait $id) -eq 0
docker commit $id $IMAGE > /dev/null
