#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

fn-git-rev-pre-receive-app() {
  declare APP="$1" IMAGE_SOURCE_TYPE="$2" TMP_WORK_DIR="$3" REV="$2"

  # Don't write the revision if there is no git repository or we have no incoming REV.
  if [[ -d "$DOKKU_ROOT/$APP/refs" ]] && [[ -n "$REV" ]]; then
    config_set --no-restart "$APP" GIT_REV="$REV"
  fi
}

fn-git-rev-pre-receive-app "$@"
