#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

main() {
  declare APP="$1" REV="$2"

  # Don't write the revision if there is no git repository.
  if [[ -d "$DOKKU_ROOT/$APP/refs" ]]; then
    config_set --no-restart "$APP" DOKKU_GIT_REV="$REV"
  fi
}

main "$@"
